language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install nose
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package=apis

after_success:
  - coveralls
