language: python

python:
  - "3.5"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install nose
  - pip install coveralls


virtualenv:
  system_site_packages: true

script:
  - pytest 

after_success:
  -coveralls
